-- rename table tran_categories 
RENAME TABLE TRAN_CATEGORIES TO TRAN_CLASSES;

ALTER TABLE TRAN_CLASSES CHANGE CATEGORY_ID CLASS_ID INT AUTO_INCREMENT;
ALTER TABLE TRAN_CLASSES CHANGE CATEGORY CLASS_NAME VARCHAR(100);

ALTER TABLE TRAN_CLASSES DROP COLUMN THREAD_ID;
ALTER TABLE TRAN_CLASSES DROP COLUMN STATUS_ID;
ALTER TABLE TRAN_CLASSES DROP COLUMN STATUS_VALUE;

-- rename table tran_question_categories 

RENAME TABLE TRAN_QUESTION_CATEGORIES TO TRAN_QUESTION_CLASSES;
ALTER TABLE TRAN_QUESTION_CLASSES CHANGE CATEGORY_ID CLASS_ID INT;
ALTER TABLE TRAN_QUESTION_CLASSES CHANGE QUESTION_CATEGORY_ID QUESTION_CLASS_ID INT AUTO_INCREMENT;

