CREATE TABLE IF NOT EXISTS `TRAN_POINTS` (
    `POINT_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `QUESTION_ID` INT(11) NOT NULL,
	`USER_ID` INT(11) NULL,
    `SUBSYSTEM_ID` INT(11) DEFAULT NULL,
	`SUBSYSTEM_VALUE` VARCHAR(10) NULL,
    `SUBSYSTEM_REFERENCE_ID` INT(11) DEFAULT NULL,
	`POINTS_TYPE_ID` INT(11) DEFAULT NULL,
    `POINTS_TYPE_VALUE` VARCHAR(10) DEFAULT NULL,
    `POINTS` INT(11) DEFAULT NULL,
    `CREATED_BY` INT(11) DEFAULT NULL,
    `CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,    
    PRIMARY KEY (`POINT_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE if not exists `TRAN_FEEDBACK` (
    `FEEDBACK_ID` int(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` int(11) NOT NULL,
    `FEEDBACK` varchar(500) NOT NULL,
    `IS_VERIFIED` varchar(10)  NULL,
    `VALUE` INT(11) DEFAULT NULL,
    `CREATED_BY` int(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` int(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,	
	`UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`FEEDBACK_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT  INTO `CURIOSITE`.`SYS_CODE` 
SELECT 11,'Action Types',null,null,null,null,null,null,'Action Types',1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE WHERE CODE_ID = 11 AND CODE_DESCRIPTION = 'Action Types');

INSERT  INTO `CURIOSITE`.`SYS_CODE` 
SELECT 12,'Point Types',null,null,null,null,null,null,'Point Types',1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE WHERE CODE_ID = 12 AND CODE_DESCRIPTION = 'Point Types');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTUQ','Vote Up Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTUQ');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTDQ','Vote Down Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTDQ');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTUA','Vote Up Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTUA');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTDA','Vote Down Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTDA');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTUC','Vote Up Comment',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTUC');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'VTDC','Vote Down Comment',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'VTDC');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 12,'VOTE','Vote Point',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 12 AND CODE_VALUE = 'VOTE');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 12,'BONS','Bonus Point',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 12 AND CODE_VALUE = 'BONS');

DELETE FROM sys_code_value WHERE CODE_ID = 9;

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 9,'UPVT','Vote Type Up',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 9 AND CODE_VALUE = 'UPVT');

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 9,'DNVT','Vote Type Down',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 9 AND CODE_VALUE = 'DNVT');

UPDATE tran_post_votes SET VOTE_VALUE ='UPVT' WHERE VOTE_VALUE = 'VTUP';
UPDATE tran_post_votes SET VOTE_VALUE ='DNVT' WHERE VOTE_VALUE = 'VTDN';

UPDATE sys_users SET EMAIL_ADDRESS = 'community.user@gmail.com', DISPLAY_NAME = 'Community User', 
LAST_NAME = 'User', NETWORK_USER_ID = 'community.user@gmail.com' WHERE EMAIL_ADDRESS = 'community.blogger@gmail.com';

UPDATE sys_users SET EMAIL_ADDRESS = 'community.user@gmail.com', DISPLAY_NAME = 'community user', 
FIRST_NAME = 'community',LAST_NAME = 'user', NETWORK_USER_ID = 'community.user@gmail.com' WHERE EMAIL_ADDRESS = 'community.user@gmail.com';

ALTER TABLE tran_post_votes ADD COLUMN `QUESTION_ID` INT(11) AFTER POST_VOTE_ID;

