INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 20,'Nothing was entered in the feedback box!!',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 20);

INSERT  INTO `CURIOSITE`.`SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 5,'INFO','Information Message',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 5 AND CODE_VALUE = 'INFO');

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 21,'Your feedback has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 21);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 22,'Your tag has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 22);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 23,'This tag already exists in the system.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 23);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 24,'Your vote has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 24);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 25,'Your comment has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 25);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 26,'Your answer has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 26);

INSERT INTO `CURIOSITE`.`SYS_MESSAGES`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 27,'Your question has been saved successfully.',5,'INFO',null,null,1,now(),1,now(),0 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGES WHERE MESSAGE_ID = 27);
