-- Message 28 - User Needs to enter announcement title
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 28,'Please enter announcement title.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 28);

-- Message 29 - User should not enter duplicate announcement
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 29,'Your announcement already exists in the system. Please enter a different title.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 29);

-- Message 30 - Announcement Description should be at least 100 Characters
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 30,'Announcement description should be at lesat 100 characters',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 30);

UPDATE sys_message SET DISPLAY_MESSAGE = 'Class name or class decription cannot be empty.' WHERE MESSAGE_ID = 19;
UPDATE sys_message SET DISPLAY_MESSAGE = 'Please enter the question title.' WHERE MESSAGE_ID = 10;

-- Message 31 - Group name and description can not be empty
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 31,'Group name or description can not be left empty.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 31);

-- Message 32 - Please add some users in the group
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 32,'Please select users from add users textbox.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 32);

-- Message 33 - Group Name already exists
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 33,'Your group name already exists in the system. Please enter a different group name.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 33);


ALTER TABLE SYS_USER ADD OTP varchar(50) NULL DEFAULT '';
ALTER TABLE SYS_USER ADD IS_USER_VERIFIED varchar(5) NULL DEFAULT '';
ALTER TABLE SYS_USER ADD IS_PASSWORD_FORGOTTEN varchar(5) NULL DEFAULT '';

ALTER TABLE SYS_USER MODIFY OTP varchar(50) AFTER PASSWORD;
ALTER TABLE SYS_USER MODIFY IS_USER_VERIFIED varchar(5) AFTER OTP;
ALTER TABLE SYS_USER MODIFY IS_PASSWORD_FORGOTTEN varchar(50) AFTER IS_USER_VERIFIED;

ALTER TABLE SYS_USER MODIFY CREATED_BY int(11) AFTER FACEBOOK_URL;
ALTER TABLE SYS_USER MODIFY CREATED_DATE DATETIME AFTER CREATED_BY;
ALTER TABLE SYS_USER MODIFY MODIFIED_BY int(11) AFTER CREATED_DATE;
ALTER TABLE SYS_USER MODIFY MODIFIED_DATE DATETIME AFTER MODIFIED_BY;
ALTER TABLE SYS_USER MODIFY UPDATE_SEQ int(11) AFTER MODIFIED_DATE;

ALTER TABLE SYS_USER ADD `USER_STATUS_ID` int(11) NOT NULL AFTER IS_USER_VERIFIED;
ALTER TABLE SYS_USER ADD `USER_STATUS_VALUE` varchar(50) DEFAULT NULL AFTER USER_STATUS_ID;


-- Code Value 18 - User Status
INSERT  INTO `SYS_CODE` 
SELECT 18,'User Status',null,null,null,null,null,null,'User Statuses',1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE WHERE CODE_ID = 18 AND CODE_DESCRIPTION = 'User Status');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 18,'ACTV','Active',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 18 AND CODE_VALUE = 'ACTV');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 18,'INAC','Inactive',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 18 AND CODE_VALUE = 'INAC');

ALTER TABLE SYS_USER MODIFY PASSWORD VARCHAR(500);
ALTER TABLE SYS_USER MODIFY OTP VARCHAR(500);
ALTER TABLE SYS_USER ADD `SALT_VALUE` varchar(500) DEFAULT NULL AFTER EMAIL_ADDRESS;

UPDATE sys_message SET DISPLAY_MESSAGE = 'Please enter email address.' WHERE MESSAGE_ID = 3;
UPDATE sys_message SET DISPLAY_MESSAGE = 'Please enter first and last name .' WHERE MESSAGE_ID = 1;

-- Message 34 - Please select role and user group for this user.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 34,'Please select role and user group for this user.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 34);

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ITCO','IT Coordinator',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ITCO');

-- Message 35 - Oops something went wrong!! system can not find your account. Please contact system administrator.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 35,'Oops something went wrong!! system can not find your account. Please contact system administrator.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 35);

-- Message 36 - Please enter the password.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 36,'Please enter the password.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 36);

UPDATE sys_message SET DISPLAY_MESSAGE = 'Your password and retyped password does not match' WHERE MESSAGE_ID = 4;
UPDATE sys_message SET DISPLAY_MESSAGE = 'Your password should be longer than at least 8 characters' WHERE MESSAGE_ID = 5;

-- Message 37 - Your password must contain some letters.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 37,'Your password must contain some letters.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 37);

-- Message 38 - Your password must contain at least one number.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 38,'Your password must contain at least one number.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 38);

-- Message 39 - Your password cannot be same as your email address.
INSERT INTO `CURIOSITE`.`SYS_MESSAGE`
(`MESSAGE_ID`,`DISPLAY_MESSAGE`,`SEVERITY_ID`,`SEVERITY_VALUE`,`INTERNAL_INSTRUCTIONS`,`USER_INSTRUCTIONS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 39,'Your password cannot be same as your email address.',5,'ERRR',null,null,1,now(),1,now(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_MESSAGE WHERE MESSAGE_ID = 39);

