CREATE TABLE if not exists `SYS_LEVEL` (
    `LEVEL_ID` int(11) NOT NULL AUTO_INCREMENT,
	`ORDER_NO` int(11) NOT NULL,
    `LEVEL_NAME` varchar(500) NOT NULL,
    `POINTS` int(11) DEFAULT NULL,
    `DESCRIPTION` varchar(500)  NULL,
    `CREATED_BY` int(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` int(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,	
	`UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`LEVEL_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Adding levels in the system - 

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 1,1,'Beginner',0,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 1);

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 2,2,'Intermediate',100,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 2);

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,3,'Semi-professional',250,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 3);

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 4,4,'Professional',1000,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 4);

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 5,5,'World Class',2500,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 5);

INSERT  INTO `CURIOSITE`.`SYS_LEVEL`
(`LEVEL_ID`,`ORDER_NO`,`LEVEL_NAME`,`POINTS`,`DESCRIPTION`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 6,6,'Legendary',10000,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_LEVEL WHERE LEVEL_ID = 6);

SELECT * FROM SYS_LEVEL;