CREATE TABLE if not exists `SYS_USER_ROLE` (
    `USER_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` int(11) NOT NULL,
	`ROLE_ID` int(11) NOT NULL,
	`ROLE_VALUE` VARCHAR(50) NULL,	
    `USER_GROUP_ID` int(11) NOT NULL,
	`USER_GROUP_VALUE` VARCHAR(50) NULL,	
    `CREATED_BY` int(11) DEFAULT NULL,
    `CREATED_DATE` DATETIME DEFAULT NULL,
	`MODIFIED_BY` int(11) DEFAULT NULL,
    `MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`USER_ROLE_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;
