CREATE TABLE if not exists `SYS_CODE_VALUE` (
    `CODE_VALUE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`CODE_ID` int(11) NOT NULL,
    `CODE_VALUE` varchar(500) NOT NULL,
    `DESCRIPTION` varchar(500)  NULL,
    `DATA1` varchar(500) DEFAULT NULL,
    `DATA2` varchar(500) NULL,
    `DATA3` varchar(500) NULL,
    `COMMENTS` varchar(50) DEFAULT NULL,
    `CREATED_BY` int(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` int(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,	
	`UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`CODE_VALUE_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- Code Value 1 - Facebook Network Type
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 1,'FACE','Facebook Network',null,null,null,'Facebook Network',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 1 AND CODE_VALUE = 'FACE');

-- Code Value 2 - Google Network Type
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 1,'GOOG','Google Network',null,null,null,'Google Network',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 1 AND CODE_VALUE = 'GOOG');

-- Code Value 3 - site Network Type
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 1,'APPC','Application Network',null,null,null,'Application Network',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 1 AND CODE_VALUE = 'APPC');

-- Code Value 3 - Twitter Network Type
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 1,'TWIT','Twitter Network',null,null,null,'Twitter Network',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 1 AND CODE_VALUE = 'TWIT');

-- Code Value 4 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 2,'MALE','Gender Male',null,null,null,'Gender Male',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 2 AND CODE_VALUE = 'MALE');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 2,'FEML','Gender Female',null,null,null,'Gender Female',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 2 AND CODE_VALUE = 'FEML');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GCIU','Google Client Id UAT','140500360968-gl23jgs6b5e9b0n052a417g66ter4e60.apps.googleusercontent.com',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GCIU');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GCIS','Google Client Id SYS','140500360968-f8t3e7pmt1e09knbdsq2jjjrr5fi4b3e.apps.googleusercontent.com',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GCIS');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GCIL','Google Client Id LOC','140500360968-qjbi53f7ie19ef4ufor51nqp6i4vt83m.apps.googleusercontent.com',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GCIL');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GAKU','Google API Key UAT','AIzaSyBnRA2rwLNKqPgdWuuPOXTR3UTaCJe9hH4',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GAKU');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GAKS','Google API Key SYS','AIzaSyDyxvLMSvnr1nfnXl_TuSvryixhJibK3Hg',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GAKS');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'GAKL','Google API Key LOC','AIzaSyCp2Jq9z9MeCQEz3F0Q_mnvX13ngZu1jEI',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'GAKL');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'FCIU','Facebook Client Id UAT','768654456560330',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'FCIU');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'FCIS','Facebook Client Id SYS','764678906943496',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'FCIS');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'FCIL','Facebook Client Id LOC','801162613266480',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'FCIL');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RDUU','Redirect URL UAT','http://www.curiositebox.com/siteAero/index.html',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RDUU');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RDUS','Redirect URL SYS','http://localhost/serviceAero/vAero/',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RDUS');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RDUL','Redirect URL LOC','http://localhost:8080/siteAero/index.html',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RDUL');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RSUU','Rest Service URL UAT','http://www.curiositebox.com/serviceAero/vAero/',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RSUU');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RSUS','Rest Service URL SYS','http://localhost/serviceAero/vAero/',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RSUS');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'RSUL','Rest Service URL LOC','http://localhost:8080/api/vAero/',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'RSUL');

-- Code Value 3 - Region
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 3,'REGN','System Envirionment','DEV',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 3 AND CODE_VALUE = 'REGN');

-- Code Value 5 - Male Gender
INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 4,'REGN','System Region Values','LOC',null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 4 AND CODE_VALUE = 'REGN');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 5,'ERRR','Error Message',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 5 AND CODE_VALUE = 'ERRR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 5,'INFO','Information Message',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 5 AND CODE_VALUE = 'INFO');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 6,'CATA','Category Status Approved',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 6 AND CODE_VALUE = 'CATA');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'INDV','Individual',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'INDV');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'CLSS','Class',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'CLSS');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'USGP','User Group',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'USGP');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 6,'CATP','Category Status Pending For Approval',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 6 AND CODE_VALUE = 'CATP');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 7,'THRA','Thread Status Approved',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 7 AND CODE_VALUE = 'THRA');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 7,'THRP','Thread Status Pending For Approval',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 7 AND CODE_VALUE = 'THRP');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 9,'UPVT','Vote Type Up',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 9 AND CODE_VALUE = 'UPVT');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 9,'DNVT','Vote Type Down',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 9 AND CODE_VALUE = 'DNVT');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 10,'QUES','Post Type Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 10 AND CODE_VALUE = 'QUES');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 10,'ANSR','Post Type Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 10 AND CODE_VALUE = 'ANSR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 10,'CMNT','Post Type Comment',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 10 AND CODE_VALUE = 'CMNT');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'UPVQ','Vote Up Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'UPVQ');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'DNVQ','Vote Down Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'DNVQ');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'UPVA','Vote Up Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'UPVA');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'DNVA','Vote Down Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'DNVA');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'UPVC','Vote Up Comment',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'UPVC');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'DNVC','Vote Down Comment',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'DNVC');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'CMTQ','Action Type - Comment on Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'CMTQ');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'ANSR','Action Type - Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'ANSR');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'CMTA','Action Type - Comment on Answer',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'CMTA');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'ASKQ','Action Type - Ask Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'ASKQ');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'MNQU','Action Type - Mentioned In Question',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'MNQU');

INSERT INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 11,'MNAN','Action Type - Mentioned In Announcement',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 11 AND CODE_VALUE = 'MNAN');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 12,'VOTE','Vote Point',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 12 AND CODE_VALUE = 'VOTE');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 12,'BONS','Bonus Point',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 12 AND CODE_VALUE = 'BONS');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 14,'GNRL','General',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 14 AND CODE_VALUE = 'GNRL');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 14,'STUD','Student',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 14 AND CODE_VALUE = 'STUD');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 14,'MDTR','Moderator',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 14 AND CODE_VALUE = 'MDTR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 14,'TCHR','Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 14 AND CODE_VALUE = 'TCHR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 14,'ADMN','Admin',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 14 AND CODE_VALUE = 'ADMN');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'FRSH','Freshman',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'FRSH');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'SPMR','Sophomore',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'SPMR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'JUNR','Junior',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'JUNR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'SENR','Senior',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'SENR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'GNRL','General',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'GNRL');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'WOLI','World Literature',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'WOLI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'EULI','European Literature',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'EULI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ENLA','English Language Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ENLA');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ENLI','English Literature Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ENLI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'WOHI','World History Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'WOHI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'HUGP','Human Geography Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'HUGP');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'PCLG','Psychology Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'PCLG');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'USHI','U.S. History Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'USHI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'CMST','Chemistry Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'CMST');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'BIOL','Biology Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'EULI');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ANTM','Anatomy Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ANTM');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'PSLG','Physiology Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'PSLG');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'PHSC','Physics Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'PHSC');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ALGB','Algebra Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ALGB');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'GMTR','Geometry Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'GMTR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'CALS','Calculus Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'CALS');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'GMTR','Geometry Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'GMTR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'STAT','Statistics Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'STAT');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'FRCH','French Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'FRCH');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'LATN','Latin Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'LATN');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'SPNS','Spanish Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'SPNS');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'FNAT','Fine Arts Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'FNAT');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'PHED','Physical Education Teacher',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'PHED');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 15,'ITCO','IT Coordinator',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 15 AND CODE_VALUE = 'ITCO');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 16,'ACTV','Active',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 16 AND CODE_VALUE = 'ACTV');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 16,'INAC','Inactive',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 16 AND CODE_VALUE = 'INAC');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'INDV','Individual',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'INDV');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'YEAR','Year',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'YEAR');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 17,'USGP','User Group',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 17 AND CODE_VALUE = 'USGP');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 18,'ACTV','Active',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 18 AND CODE_VALUE = 'ACTV');

INSERT  INTO `SYS_CODE_VALUE`
(`CODE_ID`,`CODE_VALUE`,`DESCRIPTION`,`DATA1`,`DATA2`,`DATA3`,`COMMENTS`,`CREATED_BY`,`CREATED_DATE`,`MODIFIED_BY`,`MODIFIED_DATE`,`UPDATE_SEQ`)
SELECT 18,'INAC','Inactive',null,null,null,'',1,NOW(),1,NOW(),0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CODE_VALUE WHERE CODE_ID = 18 AND CODE_VALUE = 'INAC');

