CREATE TABLE if not exists `SYS_ROLE` (
    `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`ROLE_NAME` varchar(50) NOT NULL,
	`ROLE_DESCRIPTION` varchar(50) NOT NULL,	
    `CREATED_DATE` DATETIME DEFAULT NULL,
    `CREATED_BY` int(11) DEFAULT NULL,
    `MODIFIED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` int(11) DEFAULT NULL,
    `UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`ROLE_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `CURIOSITE`.`SYS_ROLE`
(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`MODIFIED_DATE`,`MODIFIED_BY`,`UPDATE_SEQ`)
SELECT 1,'General','General',NOW(),1,NOW(),1,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_ROLE WHERE ROLE_ID = 1);

INSERT INTO `CURIOSITE`.`SYS_ROLE`
(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`MODIFIED_DATE`,`MODIFIED_BY`,`UPDATE_SEQ`)
SELECT 2,'Student','Student',NOW(),1,NOW(),1,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_ROLE WHERE ROLE_ID = 2);

INSERT INTO `CURIOSITE`.`SYS_ROLE`
(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`MODIFIED_DATE`,`MODIFIED_BY`,`UPDATE_SEQ`)
SELECT 3,'Moderator','Moderator',NOW(),1,NOW(),1,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_ROLE WHERE ROLE_ID = 3);

INSERT INTO `CURIOSITE`.`SYS_ROLE`
(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`MODIFIED_DATE`,`MODIFIED_BY`,`UPDATE_SEQ`)
SELECT 4,'Teacher','Teacher',NOW(),1,NOW(),1,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_ROLE WHERE ROLE_ID = 4);

INSERT INTO `CURIOSITE`.`SYS_ROLE`
(`ROLE_ID`,`ROLE_NAME`,`ROLE_DESCRIPTION`,`CREATED_DATE`,`CREATED_BY`,`MODIFIED_DATE`,`MODIFIED_BY`,`UPDATE_SEQ`)
SELECT 5,'Admin','Admin',NOW(),1,NOW(),1,0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_ROLE WHERE ROLE_ID = 5);