CREATE TABLE IF NOT EXISTS `TRAN_TAG_DETAIL` (
    `TAG_DETAIL_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `TAG_ID` INT(11),
    `TAGGED_USER_ID` int(11) NOT NULL,
	`CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`TAG_DETAIL_ID`)
)  
ENGINE=InnoDB DEFAULT 
COLLATE utf8_unicode_ci;
