CREATE TABLE IF NOT EXISTS `QUESTION_COMMENT` (
    `COMMENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `COMMENT_HTML` VARCHAR(2000) NOT NULL,
	`USER_ID` INT(11) NULL,
	`QUESITON_ID` INT(11) NULL,
	`CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`COMMENT_ID`)
)  
ENGINE=InnoDB DEFAULT 
COLLATE utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `ANNOUNCEMENT_COMMENT` (
    `COMMENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `COMMENT_HTML` VARCHAR(2000) NOT NULL,
	`USER_ID` INT(11) NULL,
	`ANNOUNCEMENT_ID` INT(11) NULL,
	`CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`COMMENT_ID`)
)  
ENGINE=InnoDB DEFAULT 
COLLATE utf8_unicode_ci;
