CREATE TABLE IF NOT EXISTS `TRAN_TAG` (
    `TAG_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ID` INT(11) NULL,
    `USER_GROUP_ID` int(11) NOT NULL,
	`USER_GROUP_VALUE` VARCHAR(50) NULL,	
	`SUBSYSTEM_ID` INT(11) NULL,
	`SUBSYSTEM_VALUE` VARCHAR(50) NULL,
	`SUBSYSTEM_REFERENCE_ID` INT(11) NULL,
    `CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`TAG_ID`)
)  
ENGINE=InnoDB DEFAULT 
COLLATE utf8_unicode_ci;
