CREATE TABLE IF NOT EXISTS `TRAN_REPORT_ABUSE` (
    `REPORT_ABUSE_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `ABUSE_TYPE_ID` INT(11) NULL,
	`ABUSE_TYPE_VALUE` VARCHAR(50) NULL,	
	`DESCRIPTION` VARCHAR(500) NULL,	
	`USER_ID` INT(11) NULL,
	`SUBSYSTEM_ID` INT(11) NULL,
	`SUSYSTEM_VALUE` VARCHAR(50) NULL,
	`SUBSYSTEM_REFERENCE_ID` INT(11) NULL,
    `CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`REPORT_ABUSE_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;
