CREATE TABLE IF NOT EXISTS `TRAN_ANNOUNCEMENT` (
    `ANNOUNCEMENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `USER_ID` INT(11) NULL,
    `ANNOUNCEMENT_TITLE` VARCHAR(500) NOT NULL,
	`ANNOUNCEMENT_HTML` MEDIUMTEXT NULL,
    `CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`ANNOUNCEMENT_ID`)
)  
ENGINE=InnoDB DEFAULT 
COLLATE utf8_unicode_ci;
