CREATE TABLE IF NOT EXISTS `TRAN_QUESTION_HISTORY` (
    `QUESTION_HISTORY_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `QUESTION_ID` INT(11) NOT NULL,
	`ACTION_TYPE_ID` INT(11)  NULL,
    `ACTION_TYPE_VALUE` VARCHAR(50) DEFAULT NULL,
    `USER_ID` INT(11) NULL,
    `CREATED_BY` INT(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` INT(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
    `UPDATE_SEQ` INT(11) DEFAULT NULL,
    PRIMARY KEY (`QUESTION_HISTORY_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;
