CREATE TABLE if not exists `TRAN_FEEDBACK` (
    `FEEDBACK_ID` int(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` int(11) NOT NULL,
    `FEEDBACK` varchar(500) NOT NULL,
    `IS_VERIFIED` varchar(10)  NULL,
    `VALUE` INT(11) DEFAULT NULL,
    `CREATED_BY` int(11) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL,
    `MODIFIED_BY` int(11) DEFAULT NULL,
	`MODIFIED_DATE` DATETIME DEFAULT NULL,	
	`UPDATE_SEQ` int(11) DEFAULT NULL,
    PRIMARY KEY (`FEEDBACK_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

