SELECT TF.FEEDBACK_ID,TF.FEEDBACK,TF.USER_ID,TF.VALUE,SU.DISPLAY_NAME,SU.FIRST_NAME,SU.LAST_NAME 
FROM TRAN_FEEDBACK TF 
INNER JOIN SYS_USER SU ON SU.USER_ID = TF.USER_ID
WHERE TF.USER_ID > 0 AND IS_VERIFIED = 'Y'
ORDER BY TF.VALUE DESC, TF.CREATED_DATE DESC
LIMIT 20;