--IF OBJECT_ID('tempdb..#COLUMNS') IS NOT NULL
--	DROP TABLE #COLUMNS;

---- UPDATING CREATED_DATE AND MODIFIED_DATE 
--SELECT c.name AS ColName, t.name AS TableName
--INTO #COLUMNS
--FROM sys.columns c
--INNER JOIN sys.tables t ON c.object_id = t.object_id
--WHERE C.NAME IN ('CREATED_DATE','MODIFIED_DATE')

--SELECT * FROM #COLUMNS;

--SELECT 'ALTER TABLE ' + TABLENAME + ' ADD CONSTRAINT DF_' + TABLENAME + '_' + COLNAME + ' DEFAULT GETDATE() FOR ' + COLNAME FROM #COLUMNS;

IF OBJECT_ID('tempdb..#COLUMNS') IS NOT NULL
	DROP TABLE #COLUMNS;

-- UPDATING UPDATE_SEQ
SELECT c.name AS ColName, t.name AS TableName
INTO #COLUMNS
FROM sys.columns c
INNER JOIN sys.tables t ON c.object_id = t.object_id
WHERE C.NAME IN ('UPDATE_SEQ')

SELECT * FROM #COLUMNS;

SELECT 'ALTER TABLE ' + TABLENAME + ' ADD CONSTRAINT DF_' + TABLENAME + '_' + COLNAME + ' DEFAULT 0 FOR ' + COLNAME FROM #COLUMNS;