SELECT SU.USER_ID,SU.FIRST_NAME,SU.LAST_NAME,SU.DISPLAY_NAME,SU.NETWORK_VALUE,SU.PICTURE_URL,IFNULL(SUM(TP.POINTS),0) AS POINTS,SUR.ROLE_ID,
SCV1.DESCRIPTION
FROM SYS_USER SU
LEFT JOIN TRAN_POINT TP ON TP.USER_ID = SU.USER_ID
LEFT JOIN SYS_USER_ROLE SUR ON SUR.USER_ID = SU.USER_ID
LEFT JOIN SYS_CODE_VALUE SCV ON SCV.CODE_ID = SUR.ROLE_ID AND SCV.CODE_VALUE = SUR.ROLE_VALUE
LEFT JOIN SYS_CODE_VALUE SCV1 ON SCV1.CODE_ID = SUR.USER_GROUP_ID AND SCV1.CODE_VALUE = SUR.USER_GROUP_VALUE
WHERE SU.DISPLAY_NAME LIKE ?
GROUP BY SU.USER_ID
LIMIT ?;