SELECT * FROM (
SELECT Q.QUESTION_ID AS POST_ID,'QUES' AS POST_TYPE,Q.QUESTION_TITLE AS POST_TITLE,Q.QUESTION_HTML AS POST_DESCRIPTION,Q.CREATED_BY AS USER_ID,SU.DISPLAY_NAME AS USER_NAME,
SU.PICTURE_URL AS USER_PICTURE_URL,Q.CREATED_DATE 
FROM TRAN_QUESTION Q
INNER JOIN SYS_USER SU ON SU.USER_ID = Q.CREATED_BY
UNION ALL
SELECT A.ANNOUNCEMENT_ID AS POST_ID,'ANNC' AS POST_TYPE,A.ANNOUNCEMENT_TITLE AS POST_TITLE,A.ANNOUNCEMENT_HTML AS POST_DESCRIPTION, A.CREATED_BY AS USER_ID,SU.DISPLAY_NAME AS USER_NAME,
SU.PICTURE_URL AS USER_PICTURE_URL,A.CREATED_DATE
FROM TRAN_ANNOUNCEMENT A
INNER JOIN SYS_USER SU ON SU.USER_ID = A.CREATED_BY) NEWS_FEED
ORDER BY CREATED_DATE DESC;