SELECT * FROM (
SELECT SU.DISPLAY_NAME AS LABEL,'INDV' AS USER_GROUP_TYPE,SU.USER_ID AS VALUE
FROM SYS_USER SU
LEFT JOIN SYS_USER_ROLE SUR ON SUR.USER_ID = SU.USER_ID
WHERE SUR.ROLE_VALUE IN ('TCHR'))
AS AUTOCOMPLETE_LIST
WHERE LABEL LIKE ?
LIMIT 10;
