SELECT * FROM (
SELECT SU.DISPLAY_NAME AS LABEL,'INDV' AS USER_GROUP_TYPE,SU.USER_ID AS VALUE
FROM SYS_USER SU
LEFT JOIN SYS_USER_ROLE SUR ON SUR.USER_ID = SU.USER_ID
WHERE SUR.ROLE_VALUE IN ('STUD','MDTR','TCHR')
GROUP BY SU.USER_ID
UNION ALL
SELECT CV.DESCRIPTION AS LABEL,'YEAR' AS USER_GROUP_TYPE, CV.CODE_VALUE AS VALUE 
FROM SYS_CODE_VALUE CV WHERE CODE_ID = 15 AND DATA1 = 'STUD'
UNION ALL
SELECT UG.GROUP_NAME AS LABEL,'USGP' AS USER_GROUP_TYPE, UG.USER_GROUP_ID AS VALUE 
FROM TRAN_USER_GROUP UG WHERE GROUP_STATUS_VALUE = 'ACTV')
AS AUTOCOMPLETE_LIST
WHERE LABEL LIKE ?
LIMIT 10;