SELECT * FROM(

SELECT N.NOTIFICATION_ID,N.TO_USER_ID,Q.QUESTION_ID AS REFERENCE_ID,N.SUBSYSTEM_VALUE,N.SUBSYSTEM_REFERENCE_ID,N.IS_READ,N.CREATED_DATE,N.FROM_USER_ID,
IFNULL(Q.QUESTION_TITLE,'') AS NOTIFICATION_DETAIL,SU.DISPLAY_NAME AS FROM_USER_DISPLAY_NAME,SU.PICTURE_URL AS FROM_USER_PICTURE_URL,
SU.NETWORK_VALUE
FROM TRAN_NOTIFICATION N
INNER JOIN SYS_USER SU ON SU.USER_ID = N.FROM_USER_ID
INNER JOIN TRAN_QUESTION Q ON Q.QUESTION_ID = N.SUBSYSTEM_REFERENCE_ID
WHERE SUBSYSTEM_VALUE IN ('UPVQ','DNVQ','ASKQ','MNQU')
UNION
SELECT N.NOTIFICATION_ID,N.TO_USER_ID,QA.QUESTION_ID AS REFERENCE_ID,N.SUBSYSTEM_VALUE,N.SUBSYSTEM_REFERENCE_ID,N.IS_READ,N.CREATED_DATE,N.FROM_USER_ID,
IFNULL(QA.ANSWER_HTML,'') AS NOTIFICATION_DETAIL,SU.DISPLAY_NAME AS FROM_USER_DISPLAY_NAME,SU.PICTURE_URL AS FROM_USER_PICTURE_URL,
SU.NETWORK_VALUE
FROM TRAN_NOTIFICATION N
INNER JOIN SYS_USER SU ON SU.USER_ID = N.FROM_USER_ID
INNER JOIN TRAN_QUESTION_ANSWER QA ON QA.QUESTION_ANSWER_ID = N.SUBSYSTEM_REFERENCE_ID
WHERE SUBSYSTEM_VALUE IN ('UPVA','DNVA','ANSR')
UNION
SELECT N.NOTIFICATION_ID,N.TO_USER_ID,C.SUBSYSTEM_REFERENCE_ID AS REFERENCE_ID,N.SUBSYSTEM_VALUE,N.SUBSYSTEM_REFERENCE_ID,N.IS_READ,N.CREATED_DATE,N.FROM_USER_ID,
IFNULL(C.COMMENT_HTML,'') AS NOTIFICATION_DETAIL,SU.DISPLAY_NAME AS FROM_USER_DISPLAY_NAME,SU.PICTURE_URL AS FROM_USER_PICTURE_URL,
SU.NETWORK_VALUE
FROM TRAN_NOTIFICATION N
INNER JOIN SYS_USER SU ON SU.USER_ID = N.FROM_USER_ID
INNER JOIN TRAN_COMMENT C ON C.COMMENT_ID = N.SUBSYSTEM_REFERENCE_ID
WHERE N.SUBSYSTEM_VALUE IN ('CMTQ')
UNION
SELECT N.NOTIFICATION_ID,N.TO_USER_ID,QA.QUESTION_ID AS REFERENCE_ID,N.SUBSYSTEM_VALUE,N.SUBSYSTEM_REFERENCE_ID,N.IS_READ,N.CREATED_DATE,N.FROM_USER_ID,
IFNULL(C.COMMENT_HTML,'') AS NOTIFICATION_DETAIL,SU.DISPLAY_NAME AS FROM_USER_DISPLAY_NAME,SU.PICTURE_URL AS FROM_USER_PICTURE_URL,
SU.NETWORK_VALUE
FROM TRAN_NOTIFICATION N
INNER JOIN SYS_USER SU ON SU.USER_ID = N.FROM_USER_ID
INNER JOIN TRAN_COMMENT C ON C.COMMENT_ID = N.SUBSYSTEM_REFERENCE_ID
INNER JOIN TRAN_QUESTION_ANSWER QA ON QA.QUESTION_ANSWER_ID = C.SUBSYSTEM_REFERENCE_ID
WHERE N.SUBSYSTEM_VALUE IN ('CMTA')
UNION
SELECT N.NOTIFICATION_ID,N.TO_USER_ID,A.ANNOUNCEMENT_ID AS REFERENCE_ID,N.SUBSYSTEM_VALUE,N.SUBSYSTEM_REFERENCE_ID,N.IS_READ,N.CREATED_DATE,N.FROM_USER_ID,
IFNULL(A.ANNOUNCEMENT_TITLE,'') AS NOTIFICATION_DETAIL,SU.DISPLAY_NAME AS FROM_USER_DISPLAY_NAME,SU.PICTURE_URL AS FROM_USER_PICTURE_URL,
SU.NETWORK_VALUE
FROM TRAN_NOTIFICATION N
INNER JOIN SYS_USER SU ON SU.USER_ID = N.FROM_USER_ID
INNER JOIN TRAN_ANNOUNCEMENT A ON A.ANNOUNCEMENT_ID = N.SUBSYSTEM_REFERENCE_ID
WHERE SUBSYSTEM_VALUE IN ('MNAN')

) TN WHERE TO_USER_ID = ?
ORDER BY 1 DESC
LIMIT 20