SELECT USER_TAG  FROM (
SELECT UG.GROUP_NAME AS USER_TAG, SUBSYSTEM_VALUE, SUBSYSTEM_REFERENCE_ID
FROM tran_tag T
INNER JOIN tran_user_group UG ON UG.USER_GROUP_ID = T.USER_GROUP_VALUE
WHERE USER_GROUP_TYPE_VALUE = 'USGP'
UNION ALL
SELECT CV.DESCRIPTION AS USER_TAG, SUBSYSTEM_VALUE, SUBSYSTEM_REFERENCE_ID 
FROM tran_tag T
INNER JOIN sys_code_value CV ON CV.CODE_VALUE = T.USER_GROUP_VALUE AND CV.CODE_ID = 15
WHERE USER_GROUP_TYPE_VALUE = 'YEAR'
UNION ALL
SELECT SU.DISPLAY_NAME AS USER_TAG, SUBSYSTEM_VALUE, SUBSYSTEM_REFERENCE_ID 
FROM tran_tag T
INNER JOIN tran_tag_detail TD ON TD.TAG_ID = T.TAG_ID
INNER JOIN SYS_USER SU ON SU.USER_ID = TD.TAGGED_USER_ID
WHERE USER_GROUP_TYPE_VALUE = 'INDV') 
AS USER_TAGS
WHERE SUBSYSTEM_REFERENCE_ID = ? AND SUBSYSTEM_VALUE = ?

