SELECT QUESTION_ID,QUESTION_TITLE,IS_VALID,QUESTION_ANSWER_ID,ANSWER_HTML,CREATED_DATE,SUM(VOTE) AS VOTES FROM (
SELECT TQ.QUESTION_ID,TQ.QUESTION_TITLE,TQ.IS_VALID,TQA.QUESTION_ANSWER_ID,TQA.ANSWER_HTML,TQA.CREATED_DATE,
CASE TPV.VOTE_VALUE 
WHEN 'UPVT' THEN 1
WHEN 'DNVT' THEN -1
ELSE 0
END AS VOTE
FROM TRAN_QUESTION TQ
INNER JOIN TRAN_QUESTION_ANSWER TQA ON TQA.QUESTION_ID = TQ.QUESTION_ID
LEFT JOIN TRAN_POST_VOTE TPV ON TPV.SUBSYSTEM_REFERENCE_ID = TQA.QUESTION_ANSWER_ID AND TPV.SUBSYSTEM_VALUE = 'PVTA'
WHERE TQA.CREATED_BY = ?) AS QUESTION_VOTES
GROUP BY QUESTION_ID,QUESTION_TITLE,QUESTION_ANSWER_ID,ANSWER_HTML,IS_VALID,CREATED_DATE
ORDER BY 7 DESC
LIMIT 10;