SELECT QUESTION_ID,QUESTION_TITLE,IS_VALID,CREATED_DATE,SUM(VOTE) AS VOTES FROM 
	(SELECT TQ.QUESTION_ID,TQ.QUESTION_TITLE,TQ.IS_VALID,TQ.CREATED_DATE,
	CASE TPV.VOTE_VALUE 
	WHEN 'UPVT' THEN 1
	WHEN 'DNVT' THEN -1
	ELSE 0
	END AS VOTE
	FROM TRAN_QUESTION TQ
	LEFT JOIN TRAN_POST_VOTE TPV ON TPV.SUBSYSTEM_REFERENCE_ID = TQ.QUESTION_ID AND TPV.SUBSYSTEM_VALUE = 'PVTQ'
	WHERE TQ.CREATED_BY = ?) AS QUESTION_VOTES
GROUP BY QUESTION_ID,QUESTION_TITLE,IS_VALID,CREATED_DATE
ORDER BY 5 DESC
LIMIT 10;