SELECT QUESTION_ID,QUESTION_TITLE,IS_VALID,COMMENT_ID,COMMENT_HTML,CREATED_DATE,VOTES FROM (
	SELECT QUESTION_ID,QUESTION_TITLE,IS_VALID,COMMENT_ID,COMMENT_HTML,CREATED_DATE,CREATED_BY,SUM(VOTE) AS VOTES FROM (
		SELECT TQ.QUESTION_ID,TQ.QUESTION_TITLE,TC.COMMENT_ID,TC.COMMENT_HTML,TQ.IS_VALID,TC.CREATED_DATE,TC.CREATED_BY,
		CASE TPV.VOTE_VALUE 
		WHEN 'UPVT' THEN 1
		WHEN 'DNVT' THEN -1
		ELSE 0
		END AS VOTE 
		FROM TRAN_COMMENT TC
		INNER JOIN TRAN_QUESTION TQ ON TQ.QUESTION_ID = TC.SUBSYSTEM_REFERENCE_ID
		LEFT JOIN TRAN_POST_VOTE TPV ON TPV.SUBSYSTEM_REFERENCE_ID = TC.COMMENT_ID AND TPV.SUBSYSTEM_VALUE = 'PVTC'
		WHERE TC.SUBSYSTEM_VALUE = 'QUES' ) AS COMMENT_VOTES
	GROUP BY QUESTION_ID,QUESTION_TITLE,COMMENT_ID,COMMENT_HTML,IS_VALID,CREATED_DATE,CREATED_BY
	UNION
	SELECT QUESTION_ID,QUESTION_TITLE,IS_VALID,COMMENT_ID,COMMENT_HTML,CREATED_DATE,CREATED_BY,SUM(VOTE) AS VOTES FROM (
		SELECT TQ.QUESTION_ID,TQ.QUESTION_TITLE,IS_VALID,TC.COMMENT_ID,TC.COMMENT_HTML,TC.CREATED_DATE,TC.CREATED_BY,
		CASE TPV.VOTE_VALUE 
		WHEN 'UPVT' THEN 1
		WHEN 'DNVT' THEN -1
		ELSE 0
		END AS VOTE 
		FROM TRAN_COMMENT TC
		INNER JOIN TRAN_QUESTION_ANSWER TQA ON TQA.QUESTION_ANSWER_ID = TC.SUBSYSTEM_REFERENCE_ID
		INNER JOIN TRAN_QUESTION TQ ON TQ.QUESTION_ID = TQA.QUESTION_ID
		LEFT JOIN TRAN_POST_VOTE TPV ON TPV.SUBSYSTEM_REFERENCE_ID = TC.COMMENT_ID AND TPV.SUBSYSTEM_VALUE = 'PVTC'
		WHERE TC.SUBSYSTEM_VALUE = 'ANSR' ) AS COMMENT_VOTES
	GROUP BY QUESTION_ID,QUESTION_TITLE,COMMENT_ID,COMMENT_HTML,IS_VALID,CREATED_DATE,CREATED_BY) AS COMMENTS
WHERE CREATED_BY = ?
ORDER BY 7 DESC
LIMIT 10;