SELECT IFNULL(UP_COUNT.UP_COUNT,0) - IFNULL(DN_COUNT.DN_COUNT,0) AS TOTAL_VOTES,IFNULL(UP_COUNT.UP_COUNT,0) AS UP_VOTES,IFNULL(DN_COUNT.DN_COUNT,0) AS DOWN_VOTES
FROM TRAN_QUESTION AS Q
LEFT JOIN (SELECT COUNT(*) AS UP_COUNT,SUBSYSTEM_REFERENCE_ID FROM CURIOSITE.TRAN_POST_VOTE PV
			WHERE SUBSYSTEM_VALUE = 'QUES' 
			AND VOTE_VALUE = 'UPVT'
            GROUP BY SUBSYSTEM_REFERENCE_ID) AS UP_COUNT ON UP_COUNT.SUBSYSTEM_REFERENCE_ID = Q.QUESTION_ID 
LEFT JOIN (SELECT COUNT(*) AS DN_COUNT,SUBSYSTEM_REFERENCE_ID FROM CURIOSITE.TRAN_POST_VOTE PV
			WHERE SUBSYSTEM_VALUE = 'QUES' 
			AND VOTE_VALUE = 'DNVT'
            GROUP BY SUBSYSTEM_REFERENCE_ID) AS DN_COUNT ON DN_COUNT.SUBSYSTEM_REFERENCE_ID = Q.QUESTION_ID 
WHERE QUESTION_ID = ?
