SELECT Q.QUESTION_ID,Q.QUESTION_HTML,Q.QUESTION_TITLE,Q.CREATED_DATE,SU.USER_ID,SU.DISPLAY_NAME,SU.PICTURE_URL,SU.FIRST_NAME,SU.LAST_NAME,SU.NETWORK_VALUE,
IFNULL(QA.COUNT_OF_ANSWERS,0) AS COUNT_OF_ANSWERS,IFNULL(QV.COUNT_OF_VIEWS,0) AS COUNT_OF_VIEWS,PNTS.POINTS,SCV.DESCRIPTION
FROM TRAN_QUESTION Q
LEFT JOIN SYS_USER SU ON SU.USER_ID = Q.CREATED_BY
LEFT JOIN SYS_USER_ROLE SUR ON SUR.USER_ID = SU.USER_ID
LEFT JOIN SYS_CODE_VALUE SCV ON SCV.CODE_ID = SUR.USER_GROUP_ID AND SCV.CODE_VALUE = SUR.USER_GROUP_VALUE
LEFT OUTER JOIN (SELECT QAIn.QUESTION_ID,COUNT(QAIn.QUESTION_ANSWER_ID) AS COUNT_OF_ANSWERS 
						FROM TRAN_QUESTION_ANSWER QAIn 
						GROUP BY QAIn.QUESTION_ID ) AS QA ON QA.QUESTION_ID = Q.QUESTION_ID  
LEFT OUTER JOIN (SELECT QVIn.QUESTION_ID,COUNT(QVIn.QUESTION_VIEW_ID) AS COUNT_OF_VIEWS 
						FROM TRAN_QUESTION_VIEW QVIn 
						GROUP BY QVIn.QUESTION_ID ) AS QV ON QV.QUESTION_ID = Q.QUESTION_ID  
LEFT OUTER JOIN (SELECT SUIN.USER_ID,IFNULL(SUM(TP.POINTS),0) AS POINTS 
							FROM SYS_USER SUIN
							LEFT JOIN TRAN_POINT TP ON TP.USER_ID = SUIN.USER_ID
							GROUP BY SUIN.USER_ID ) AS PNTS ON PNTS.USER_ID = SU.USER_ID
GROUP BY Q.QUESTION_ID,QA.COUNT_OF_ANSWERS
ORDER BY Q.CREATED_DATE DESC,Q.MODIFIED_DATE DESC
LIMIT 100