SELECT 
Q.*,IFNULL(QA.COUNT_OF_ANSWERS,0) AS COUNT_OF_ANSWERS,IFNULL(C.COUNT_OF_COMMENTS,0) AS COUNT_OF_COMMENTS
FROM TRAN_QUESTION Q
LEFT OUTER JOIN (SELECT QAIn.QUESTION_ID,COUNT(QAIn.QUESTION_ANSWER_ID) AS COUNT_OF_ANSWERS FROM TRAN_QUESTION_ANSWER QAIn 
						GROUP BY QAIn.QUESTION_ID ) AS QA ON QA.QUESTION_ID = Q.QUESTION_ID  
LEFT OUTER JOIN (SELECT CIn.SUBSYSTEM_REFERENCE_ID,COUNT(CIn.COMMENT_ID) AS COUNT_OF_COMMENTS FROM TRAN_COMMENT CIn 
						WHERE CIn.SUBSYSTEM_ID = 8 AND CIn.SUBSYSTEM_VALUE = 'QUES' 
						GROUP BY CIn.SUBSYSTEM_REFERENCE_ID) AS C ON C.SUBSYSTEM_REFERENCE_ID = Q.QUESTION_ID
WHERE Q.THREAD_ID = ?                      
GROUP BY Q.QUESTION_ID
ORDER BY COUNT_OF_ANSWERS DESC,COUNT_OF_COMMENTS DESC;