-- converting data type of comment_html in tran_comments table from varchar to TEXT

ALTER TABLE TRAN_COMMENTS ADD COMMENT_HTML_NEW TEXT;

UPDATE TRAN_COMMENTS SET COMMENT_HTML_NEW = COMMENT_HTML; 

ALTER TABLE TRAN_COMMENTS DROP COMMENT_HTML;

ALTER TABLE TRAN_COMMENTS CHANGE COMMENT_HTML_NEW COMMENT_HTML TEXT;

SELECT COMMENT_HTML FROM TRAN_COMMENTS;

-- converting data type of answer_html in tran_question_answer from varchar to TEXT

ALTER TABLE TRAN_QUESTION_ANSWERS ADD ANSWER_HTML_NEW TEXT;

UPDATE TRAN_QUESTION_ANSWERS SET ANSWER_HTML_NEW = ANSWER_HTML; 

ALTER TABLE TRAN_QUESTION_ANSWERS DROP ANSWER_HTML;

ALTER TABLE TRAN_QUESTION_ANSWERS CHANGE ANSWER_HTML_NEW ANSWER_HTML TEXT;

SELECT ANSWER_HTML FROM TRAN_QUESTION_ANSWERS;

-- converting data type of question_html in tran_question_ from varchar to TEXT

ALTER TABLE TRAN_QUESTIONS ADD QUESTION_HTML_NEW TEXT;

UPDATE TRAN_QUESTIONS SET QUESTION_HTML_NEW = QUESTION_HTML; 

ALTER TABLE TRAN_QUESTIONS DROP QUESTION_HTML;

ALTER TABLE TRAN_QUESTIONS CHANGE QUESTION_HTML_NEW QUESTION_HTML TEXT;

SELECT QUESTION_HTML FROM TRAN_QUESTIONS;
